# Generated by Django 2.2.5 on 2019-10-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='instructor',
            new_name='instructor_instance',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='class_id',
            new_name='class_instance',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='student_id',
            new_name='student_instance',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='class_id',
            new_name='class_instance',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='receiver_instance',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='sender_instance',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='class_id',
            new_name='class_instance',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='student_id',
            new_name='student_instance',
        ),
        migrations.RenameField(
            model_name='skill_label',
            old_name='class_id',
            new_name='class_instance',
        ),
        migrations.RenameField(
            model_name='skill_label',
            old_name='student_id',
            new_name='student_instance',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='<django.db.models.fields.BigIntegerField>', max_length=20),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='group_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
