# Generated by Django 2.2.5 on 2019-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191005_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
