# Generated by Django 2.2.5 on 2019-10-03 18:19

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('students', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('name', models.CharField(default=None, max_length=200, unique=True)),
                ('description', models.CharField(default=None, max_length=2000)),
                ('instructor', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
